AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation Template for Roman Numerals Converter Application. This template creates Python Flask Web Application on Amazon Linux 2 (ami-0022f774911c1d690) EC2 Instance with custom security group allowing http connections on port 80 and SSH connection on port 22. Roman Numerals Converter Application is downloaded from Github repository, then installed on Flask.
Parameters:
  myKeyName:
    Description: Key Name
    Type: AWS::EC2::KeyPair::KeyName
    Default: instancekey
    ConstraintDescription: Please select key pair.
  
  myAMI:
    Description: 
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  myInstanceType:
    Description: EC2 Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium
    ConstraintDescription: Please select a valid instance type.

Resources:
  mySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows http connection  # Required
      GroupName: "String"
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: TCP
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: TCP
          ToPort: 22
      Tags: 
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack

  myInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref myAMI
      InstanceType: !Ref myInstanceType
      KeyName: !ref myKeyName
      SecurityGroupIds: 
        -  !Ref mySG
      Tags: 
        - Key: Name
          Value: web-server-of-stackname
      UserData: !Base64 |
        #! /bin/bash
        yum update -y
        yum install python3 -y
        pip3 install flask
        cd /home/ec2-user
        wget https://raw.githubusercontent.com/ilhanigit/001-roman-numerals-converter/master/roman-numerals-converter-app.py
        mkdir templates
        cd templates
        wget https://raw.githubusercontent.com/ilhanigit/001-roman-numerals-converter/master/templates/index.html
        https://raw.githubusercontent.com/ilhanigit/001-roman-numerals-converter/master/templates/result.html
        cd ..
        python3 app.py

Outputs: 
  WebSiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt myInstance.PublicDnsName
    Description: Roman Numerals Converter Application URL
  









